services:
  - type: web
    name: vecho-hub
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DISCORD_CLIENT_ID
        value: 1359842739835170886
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        value: https://vecho-hub.onrender.com/auth/discord/callback
    plan: free
    region: oregon
